[2023-02-17 13:42:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 13:42:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 13:42:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 13:42:37] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":56,"PacketSent":49,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676612544}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 13:42:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 13:42:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 13:42:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 13:47:46] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2023-02-17 13:48:37] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 2 次重试 
[2023-02-17 13:53:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 将进行第 1 次重试 
[2023-02-17 14:02:41] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:02:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:02:49] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:02:52] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":58,"PacketSent":50,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613759}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:02:54] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:02:58] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:03:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:03:05] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":58,"PacketSent":50,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613772}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:03:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:03:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:03:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:03:17] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":59,"PacketSent":51,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613785}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:03:19] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:03:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:03:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:03:30] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":59,"PacketSent":51,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613797}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:03:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:03:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:03:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:03:43] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":59,"PacketSent":51,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613810}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:03:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:03:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:03:52] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:03:55] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":60,"PacketSent":52,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613823}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:03:57] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:04:01] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:04:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:04:08] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":60,"PacketSent":52,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613835}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:04:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:04:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:04:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:04:20] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":61,"PacketSent":53,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613848}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:04:22] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:04:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:04:30] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:04:33] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":61,"PacketSent":53,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613860}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:04:35] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:04:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:04:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:04:46] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":62,"PacketSent":54,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613873}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:04:48] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:04:51] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:04:55] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:04:58] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":62,"PacketSent":54,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613886}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:05:00] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:05:04] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:05:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:05:11] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":62,"PacketSent":54,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613898}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:05:13] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:05:17] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:05:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:05:24] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":63,"PacketSent":55,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613911}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:05:26] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:05:29] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:05:33] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:05:36] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":63,"PacketSent":55,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613924}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:05:38] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:05:42] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:05:45] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:06:07] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:06:10] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:06:14] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:06:18] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":56,"PacketSent":49,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613965}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:06:20] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:06:23] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:06:27] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2023-02-17 14:06:30] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":3184158662,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":56,"PacketSent":49,"PacketLost":0,"MessageReceived":0,"MessageSent":0,"LastMessageTime":0,"DisconnectTimes":0,"LostTimes":0}},"time":1676613978}
 到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2023-02-17 14:06:32] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2023-02-17 14:06:36] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2023-02-17 14:06:39] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5800/ 失败: Post "http://127.0.0.1:5800/": dial tcp 127.0.0.1:5800: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
